apiVersion: apps/v1
kind: Deployment
metadata:
  name: labfinal-deployment
  labels:
    app: lab-final
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-final
  template:
    metadata:
      labels:
        app: lab-final
    spec:
      containers:
      - name: lab-final
        image: z4nd3r/labfinal:latest
        ports:
        - containerPort: 8085
