apiVersion: apps/v1
kind: Deployment
metadata:
  name: labfinal-deployment
  labels:
    app: labfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labfinal
  template:
    metadata:
      labels:
        app: labfinal
    spec:
      containers:
      - name: labfinal
        image: z4nd3r/labfinal:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8086
