apiVersion: apps/v1
kind: Deployment
metadata:
  name: labfinal
  labels:
    app: labfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labfinal
  template:
    metadata:
      labels:
        app: labfinal
    spec:
      containers:
      - name: labfinal
        image: z4nd3r/labfinal:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: labfinal-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: labfinal
  type: LoadBalancer
