name: Cambiar mensaje

on:
  
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
          ls build/libs
          
          
      - name: Code Review
        env:
           SONAR_TOKEN: ${{ secrets.TOKEN_SONARCLOUD_LAB }}
        run: |
           chmod +x gradlew
           ./gradlew build sonar --info    
        
      - name: Copia de JAR
        run: |
          cp $GITHUB_WORKSPACE/build/libs/labfinal-0.0.1.jar .
          pwd
          ls -l
          chmod 777 ./labfinal-0.0.1.jar
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build y push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: z4nd3r/labfinal:latest

  deploy:

    runs-on: self-hosted
    needs: build
    steps:

    - uses: actions/checkout@v3
    
    - name: Deploy in Minikube
      run: |
        kubectl apply -f deployment.yml
