name: CI
on:
  
 push:
  branches: [ "feature-ms-carlosvillanueva-mensaje" ]
 pull_request:
  branches: [ "feature-ms-carlosvillanueva-mensaje" ]
  
 workflow_dispatch:
jobs:
  
 build:
   
  runs-on: ubuntu-latest
  
  steps:
   
   - uses: actions/checkout@v3
   # prueba
   - name: Build
     run: |
      echo "Construyendo"
      chmod +x gradlew
      ./gradlew build
      ls -ltr

   - name: SonarCloud Analysis
     run: |
       chmod +x gradlew 
       ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD_LAB }} 
   - name: Docker Login
     uses: docker/login-action@v2.2.0
     with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
   - name: Copia de Jar a Raiz de proyecto
     run: |
      ls -lt
      cp $GITHUB_WORKSPACE/build/libs/spring-petclinic-2.6.0.jar .
      chmod 777 spring-petclinic-2.6.0.jar
      ls -lt
      
   - name: Docker Build
     run: |
       docker build --tag z4nd3r/labfinal:latest .
       docker images
       
   - name: Docker Push
     run: |
       docker push z4nd3r/labfinal:latest
       
  deploy:
   runs-on: self-hosted
   needs: build
   steps:

   - name: Deploy a Minikube
     run: |
       kubectl apply -f deployment.yml
       
