name: CI
on:
  
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]
  
 workflow_dispatch:
jobs:
  
 build:
   
  runs-on: ubuntu-latest
  
  steps:
   
   - uses: actions/checkout@v3
   # prueba
   - name: Build
     run: |
      echo "Construyendo"
 test:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: SonarCloud Analysis
       run: |
         chmod +x gradlew 
         ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD_LAB }} 
       
